language: python
sudo: false
env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-djdev
  - TOXENV=py36-dj18
  - TOXENV=py36-dj19
  
  - TOXENV=py36-dj110
  - TOXENV=py36-djdev
matrix:
  allow_failures:
    - env: TOXENV=py27-djdev
    - env: TOXENV=py36-djdev
install:
  - pip install tox


#before_script:
  #- export DJANGO_LIVE_TEST_SERVER_ADDRESS=localhost:8000-8010,8080,9200-9300
  #- export DJANGO_TEST_PROCESSES=1
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- python manage.py runserver &
  #- sleep 3 # give django server time to bind to sockets


script:
  - tox

#after_success:
#  - coverage combine
#  - codecov
